
#---standard pioneer footprint---
#---(in meters)---
#footprint: [ [0.254, -0.0508], [0.1778, -0.0508], [0.1778, -0.1778], [-0.1905, -0.1778], [-0.254, 0], [-0.1905, 0.1778], [0.1778, 0.1778], [0.1778, 0.0508], [0.254, 0.0508] ]
footprint: [ [-0.33,-0.14], [0.33,-0.14], [0.33,0.14], [-0.33,0.14] ]
#footprint: [ [-0.55,-0.18], [0.45,-0.18], [0.45,0.18], [-0.55,0.18] ]
#footprint: [ [-0.01,-0.0125], [0.05,-0.0125], [0.05,0.0125], [-0.01,0.0125] ]

transform_tolerance: 0.5
map_type: costmap

obstacle_layer:
 enabled: true
 obstacle_range: 5.0
 raytrace_range: 5.5
 inflation_radius: 0.3
 track_unknown_space: false
 combination_method: 1

 observation_sources: laser_scan_sensor
 laser_scan_sensor: {data_type: LaserScan, topic: scan, marking: true, clearing: true}


inflation_layer:
  enabled:              true
  cost_scaling_factor:  10.0  # exponential rate at which the obstacle cost drops off (default: 10)
  inflation_radius:     2.5  # max. distance from an obstacle at which costs are incurred for planning paths.

static_layer:
  enabled:              true
  map_topic:            "/map"
